[tool.poetry]
name = "singlecellrnasignature"
version = "0.2.0"
description = ""
authors = ["Lukas Jonathan Haeuser <lhaeuser@ethz.ch>"]
readme = "README.md"
packages = [{ include = "singlecellrnasignature" }]
include = ["singlecellrnasignature/py.typed"]

[tool.poetry.dependencies]
python = "^3.12"
datalair = {git = "https://github.com:LuJoHae/datalair.git"}
polars = "^1.34.0"
anndata = "^0.12.2"
numpy = "^2.3.3"
pandas = "^2.3.3"
scipy = "^1.16.2"
scanpy = "^1.11.4"
pandas-stubs = "~=2.3.3"
ipykernel = "^7.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
mypy = "^1.18.2"
pandas-stubs = "^2.3.2.250926"
scipy-stubs = "^1.16.2.3"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.22"
mkdocstrings = "^0.30.1"
mkdocstrings-python = "^1.18.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.mypy]
python_version = "3.12"
strict = true

[[tool.mypy.overrides]]
module = ["scanpy", "scanpy.*", "anndata", "anndata.*"]
ignore_missing_imports = true